from abc import ABC, abstractmethod
from llama_cpp import Llama


class ILlmLoaderRepository(ABC):
    @abstractmethod
    async def load_model(
        self,
    ) -> Llama: ...

    async def unload_model(self, model: Llama): ...
    async def response(self, model: Llama, text: str) -> str: ...
    async def chat(self, text: str) -> str: ...
