"""chatdata addition

Revision ID: 4880eb1ecbb6
Revises: 514e3de40832
Create Date: 2025-02-10 22:40:07.161631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4880eb1ecbb6'
down_revision: Union[str, None] = '514e3de40832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_path_id', sa.Integer(), nullable=False),
    sa.Column('full_chat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_path_id'], ['chatpath.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chatpath', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chatpath', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatpath', 'updated_at')
    op.drop_column('chatpath', 'created_at')
    op.drop_table('chatdata')
    # ### end Alembic commands ###
