from abc import ABC, abstractmethod


class IPathContextRepository(ABC):
    @abstractmethod
    async def summarize(self, response_string: str, model_path: str) -> str: ...
    async def get_summaries(self, path: str) -> str: ...
    async def limit_context(self, text: str) -> str: ...
    async def create_context_path(self, path: str) -> str: ...
    async def has_path(self, path: str) -> str | None: ...
    async def add_context(self, path: str, full_chat: str, summary: str) -> str: ...
