from abc import ABC, abstractmethod


class IPathContextRepository(ABC):
    @abstractmethod
    async def summarize(self, response_string: str, model_path: str) -> str: ...
    async def get_summaries(self) -> str: ...
    async def limit_context(self, text: str) -> str: ...
